"""
This type stub file was generated by pyright.
"""

from tensorflow_probability.python.experimental.bayesopt import acquisition
from tensorflow_probability.python.internal import all_util

"""TensorFlow Probability experimental Bayesopt package."""
_allowed_symbols = ...
