"""
This type stub file was generated by pyright.
"""

from tensorflow_probability.python.math.psd_kernels import feature_transformed

"""Kumaraswamy CDF transformed kernel."""
__all__ = ['KumaraswamyTransformed']
class KumaraswamyTransformed(feature_transformed.FeatureTransformed):
  """Transform inputs by Kumaraswamy bijector.

  Uses Kumaraswamy bijector to warp features. The purpose of this is to is turn
  a stationary kernel in to a non-stationary one. Note that this kernel requires
  inputs to be in `[0, 1]` (the domain of the bijector).
  """
  def __init__(self, kernel, concentration1, concentration0, validate_args=..., name=...) -> None:
    """Construct a KumaraswamtTransformed kernel instance.

    This kernel wraps a kernel `k`, pre-transforming inputs with an
    Kumaraswamy bijector's `inverse` function before passign off to `k`.

    Args:
      kernel: The `PositiveSemidefiniteKernel` instance to transform.
      concentration1: forwarded to the concentration1 parameter of the
        Kumaraswamy bijector.
      concentration0: forwarded to the concentration0 parameter of the
        Kumaraswamy bijector.
      validate_args: forwarded to the `validate_args` parameter of the
        Kumaraswamy bijector.
      name: Python `str` name given to ops managed by this object.
    """
    ...
  
  @property
  def concentration1(self):
    ...
  
  @property
  def concentration0(self):
    ...
  
  def __getitem__(self, slices): # -> Self:
    ...
  


