"""
This type stub file was generated by pyright.
"""

from tensorflow_probability.python.layers.conv_variational import Convolution1DFlipout, Convolution1DReparameterization, Convolution2DFlipout, Convolution2DReparameterization, Convolution3DFlipout, Convolution3DReparameterization
from tensorflow_probability.python.layers.dense_variational import DenseFlipout, DenseLocalReparameterization, DenseReparameterization
from tensorflow_probability.python.layers.dense_variational_v2 import DenseVariational
from tensorflow_probability.python.layers.distribution_layer import CategoricalMixtureOfOneHotCategorical, DistributionLambda, IndependentBernoulli, IndependentLogistic, IndependentNormal, IndependentPoisson, KLDivergenceAddLoss, KLDivergenceRegularizer, MixtureLogistic, MixtureNormal, MixtureSameFamily, MultivariateNormalTriL, OneHotCategorical, VariationalGaussianProcess
from tensorflow_probability.python.layers.initializers import BlockwiseInitializer
from tensorflow_probability.python.layers.masked_autoregressive import AutoregressiveTransform
from tensorflow_probability.python.layers.util import default_loc_scale_fn, default_mean_field_normal_fn, default_multivariate_normal_fn
from tensorflow_probability.python.layers.variable_input import VariableLayer

"""Probabilistic Layers."""
_allowed_symbols = ...
