"""
This type stub file was generated by pyright.
"""

from tensorflow_probability.python.internal.backend.numpy import composite_tensor

"""Numpy stub for `tf.__internal__`."""
__all__ = ['CompositeTensor']
CompositeTensor = composite_tensor.CompositeTensor
