"""
This type stub file was generated by pyright.
"""

import contextlib

"""Stub implementation of tensorflow.python.util.deprecation."""
def deprecated_alias(deprecated_name, name, func_or_class, warn_once=...):
  ...

def deprecated_endpoints(*args): # -> Callable[..., Any]:
  ...

def deprecated(date, instructions, warn_once=...): # -> Callable[..., Any]:
  ...

def deprecated_args(date, instrutions, *deprecated_arg_names_or_tuples, **kwargs): # -> Callable[..., Any]:
  ...

def deprecated_arg_values(date, instructions, warn_once=..., **deprecated_kwargs): # -> Callable[..., Any]:
  ...

def deprecated_argument_lookup(new_name, new_value, old_name, old_value):
  ...

@contextlib.contextmanager
def silence(): # -> Generator[None, Any, None]:
  ...

