"""
This type stub file was generated by pyright.
"""

import contextlib

"""Utility functions for dealing with `tf.name_scope` names."""
__all__ = ['camel_to_lower_snake', 'get_name_scope_name', 'instance_scope']
_IN_INSTANCE_SCOPE = ...
_valid_chars_re = ...
_camel_snake_re = ...
def strip_invalid_chars(name): # -> str:
  ...

def camel_to_lower_snake(name): # -> str:
  ...

def get_name_scope_name(name):
  """Returns the input name as a unique `tf.name_scope` name."""
  ...

@contextlib.contextmanager
def instance_scope(instance_name, constructor_name_scope): # -> Generator[Any, Any, None]:
  """Constructs a name scope for methods of a distribution (etc.) instance."""
  ...

