"""
This type stub file was generated by pyright.
"""

"""Slicing utility for TFP objects with batch shape (tfd.Distribution, etc)."""
__all__ = ['batch_slice']
PROVENANCE_ATTR = ...
def batch_slice(batch_object, params_overrides, slices, bijector_x_event_ndims=...): # -> Any:
  """Slices `batch_object` along its batch dimensions.

  Args:
    batch_object: A `tfd.Distribution` instance.
    params_overrides: A `dict` of parameter overrides. (e.g. from
      `Distribution.copy`).
    slices: A `slice` or `int` or `int` `Tensor` or `tf.newaxis` or `tuple`
      thereof. (e.g. the argument of a `__getitem__` method).
    bijector_x_event_ndims: If `batch_object` is a bijector, this is the
      (structure of) integer(s) value of `x_event_ndims` in the current context
      (for example, as passed to `experimental_batch_shape`). Otherwise, this
      argument should be `None`.
      Default value: `None`.

  Returns:
    new_batch_object: A batch-sliced `tfd.Distribution`.
  """
  ...

