"""
This type stub file was generated by pyright.
"""

import tf_keras.api._v1.keras.__internal__.legacy.layers as tf1_layers
import tf_keras.api._v1.keras as v1
from tf_keras import *
from tensorflow.compat.v2.keras import *

"""Utility for importing the correct version of Keras."""
_keras_version_fn = ...
_use_tf_keras = ...
if _use_tf_keras:
  ...
else:
  v1 = ...
  tf1_layers = ...
