"""
This type stub file was generated by pyright.
"""

from tensorflow_probability.python.experimental.tangent_spaces import spaces

"""Tangent Spaces related to simplices."""
class ProbabilitySimplexSpace(spaces.TangentSpace):
  """Tangent space of M for Simplex distributions in R^n."""
  def compute_basis(self, x): # -> LinearOperatorBasis:
    """Returns a `TangentSpace` of a n-simplex."""
    ...
  


