"""
This type stub file was generated by pyright.
"""

from tensorflow_probability.python.bijectors import bijector as bijector_lib

"""The GeneralizedPareto bijector."""
__all__ = ['GeneralizedPareto']
class GeneralizedPareto(bijector_lib.CoordinatewiseBijectorMixin, bijector_lib.AutoCompositeTensorBijector):
  """Bijector mapping R**n to non-negative reals.

  Forward computation maps R**n to the support of the `GeneralizedPareto`
  distribution with parameters `loc`, `scale`, and `concentration`.

  #### Mathematical Details

  The forward computation from `y` in R**n to `x` constrains `x` as follows:

  `x >= loc`                                             if `concentration >= 0`
  `x >= loc` and `x <= loc + scale / abs(concentration)` if `concentration < 0`

  This bijector is used as the `experimental_default_event_space_bijector` of
  the `GeneralizedPareto` distribution.

  """
  def __init__(self, loc, scale, concentration, validate_args=..., name=...) -> None:
    ...
  
  @property
  def loc(self):
    ...
  
  @property
  def scale(self):
    ...
  
  @property
  def concentration(self):
    ...
  


