"""
This type stub file was generated by pyright.
"""

from tensorflow_probability.python.bijectors import bijector

"""Moyal bijector."""
__all__ = ['MoyalCDF']
class MoyalCDF(bijector.CoordinatewiseBijectorMixin, bijector.AutoCompositeTensorBijector):
  """Compute `Y = g(X) = erfc(exp(- 1/2 * (X - loc) / scale) / sqrt(2))`.

  This bijector maps inputs from `[-inf, inf]` to `[0, 1]`. The inverse of the
  bijector applied to a uniform random variable `X ~ U(0, 1)` gives back a
  random variable with the Moyal distribution:

  ```none
  Y ~ MoyalCDF(loc, scale)
  pdf(y; loc, scale) = exp(
    - 1/2 * ( (y - loc) / scale + exp(- (y - loc) / scale) ) ) /
    (sqrt(2 * pi) * scale)
  ```
  """
  def __init__(self, loc=..., scale=..., validate_args=..., name=...) -> None:
    """Instantiates the `MoyalCDF` bijector.

    Args:
      loc: Float-like `Tensor` that is the same dtype and is
        broadcastable with `scale`.
        This is `loc` in
        `Y = g(X) = erfc(exp(- 1/2 * (X - loc) / scale) / sqrt(2))`.
      scale: Positive Float-like `Tensor` that is the same dtype and is
        broadcastable with `loc`.
        This is `scale` in
        `Y = g(X) = erfc(exp(- 1/2 * (X - loc) / scale) / sqrt(2))`.
      validate_args: Python `bool` indicating whether arguments should be
        checked for correctness.
      name: Python `str` name given to ops managed by this object.
    """
    ...
  
  @property
  def loc(self):
    """The loc of the Moyal distribution."""
    ...
  
  @property
  def scale(self):
    """The scale of the Moyal distribution."""
    ...
  


