"""
This type stub file was generated by pyright.
"""

from tensorflow_probability.python.internal import all_util
from tensorflow_probability.python.sts.components import *
from tensorflow_probability.python.sts.decomposition import decompose_by_component, decompose_forecast_by_component
from tensorflow_probability.python.sts.fitting import build_factored_surrogate_posterior, build_factored_surrogate_posterior_stateless, fit_with_hmc, sample_uniform_initial_state
from tensorflow_probability.python.sts.forecast import forecast, impute_missing_values, one_step_predictive
from tensorflow_probability.python.sts.internal.missing_values_util import MaskedTimeSeries, moments_of_masked_time_series
from tensorflow_probability.python.sts.regularization import MissingValuesTolerance, regularize_series
from tensorflow_probability.python.sts.structural_time_series import StructuralTimeSeries

"""Framework for Bayesian structural time series models.

See the [blog post](
https://blog.tensorflow.org/2019/03/structural-time-series-modeling-in.html)
for an introductory example.
"""
_allowed_symbols = ...
