"""
This type stub file was generated by pyright.
"""

"""Utilities for computing losses."""
__all__ = ['kl_divergence_monte_carlo', 'kl_divergence_exact', 'negloglik', 'compute_extra_loss']
def kl_divergence_monte_carlo(q, r, w):
  """Monte Carlo KL Divergence."""
  ...

def kl_divergence_exact(q, r, w):
  """Exact KL Divergence."""
  ...

def negloglik(x, y, model_fn, axis=...):
  """Negative log-likelihood."""
  ...

def compute_extra_loss(layer, loss_fn=...): # -> float:
  ...

