"""
This type stub file was generated by pyright.
"""

from tensorflow_probability.python.distributions import distribution

"""Matrix T distribution classes."""
__all__ = ['MatrixTLinearOperator']
class MatrixTLinearOperator(distribution.AutoCompositeTensorDistribution):
  """The Matrix T distribution on `n x p` matrices.

  The Matrix T distribution is defined over `n x p` matrices and
  parameterized by a (batch of) `n x p` `loc` matrices, a (batch of) `n x n`
  `scale_row` matrix and a (batch of) `p x p` `scale_column` matrix.

  #### Mathematical Details

  The probability density function (pdf) is,

  ```none
  pdf(x; df, loc, scale_row, scale_column) =
     mvt_pdf(vec(x); df, vec(loc), scale_column (x) scale_row)
  ```

  where:

  * `df` is the degrees of freedom parameter.
  * `loc` is a `n x p` matrix,
  * `scale_row` is a linear operator in `R^{n x n}`, such that the covariance
    between rows can be expressed as `row_cov = scale_row @ scale_row.T`,
  * `scale_column` is a linear operator in `R^{p x p}`, such that the covariance
    between columns can be expressed as
    `col_cov = scale_column @ scale_column.T`,
  * `mvt_pdf` is the Multivariate T probability density function.
  * `vec` is the operation that converts a matrix to a column vector (
    in numpy terms this is `X.T.flatten()`)
  * `(x)` is the Kronecker product.

  #### Examples

  ```python
  tfd = tfp.distributions

  # Initialize a single 2 x 3 Matrix T.
  mu = [[1., 2, 3], [3., 4, 5]]
  col_cov = [[ 0.36,  0.12,  0.06],
             [ 0.12,  0.29, -0.13],
             [ 0.06, -0.13,  0.26]]
  scale_column = tf.linalg.LinearOperatorTriL(tf.cholesky(col_cov))
  # ==> [[ 0.6,  0. ,  0. ],
  #      [ 0.2,  0.5,  0. ],
  #      [ 0.1, -0.3,  0.4]])
  scale_row = tf.linalg.LinearOperatorDiag([0.9, 0.8])

  mvn = tfd.MatrixTLinearOperator(
      df=2.,
      loc=mu,
      scale_row=scale_row,
      scale_column=scale_column)

  # Initialize a 4-batch of 2 x 5-variate Matrix Ts.
  mu = tf.ones([2, 3, 5])
  scale_column_diag = [1., 2., 3., 4., 5.]
  scale_row_diag = [[0.3, 0.4, 0.6], [1., 2., 3.]]

  mvn = tfd.MatrixTLinearOperator(
      df=[1., 2., 3., 4.],
      loc=mu,
      scale_row=tf.linalg.LinearOperatorDiag(scale_row_diag),
      scale_column=tf.linalg.LinearOperatorDiag(scale_column_diag))
  ```

  NOTE: This Matrix-T distribution is parameterized slightly differently than
  the literature. Specifically, the parameterization is such that it is
  consistent with the vector case of a Multivariate Student-T.
  This also ensures that in the limit as `df` goes to infinity, we recover the
  Matrix-Normal distribution.

  The usual parameterization can be recovered by multiplying a scale factor
  by `sqrt(1. / df)` (which will in turn scale the `variance` and `covariance`
  by `1. / df`.


  #### References

  [1] G. Arjun, N. Daya, "Matrix Variate Distributions",
      Vol. 104. CRC Press.
  """
  def __init__(self, df, loc, scale_row, scale_column, validate_args=..., allow_nan_stats=..., name=...) -> None:
    """Construct Matrix T distribution on `R^{n x p}`.

    The `batch_shape` is the broadcast shape between `loc`, `scale_row`
    and `scale_column` arguments.

    The `event_shape` is given by the matrix implied by `loc`.

    Args:
      df: Floating-point `Tensor`, having shape `[B1, ..., Bb]` representing
        the degrees of freedom parameter. Has same `dtype` as `loc`.
      loc: Floating-point `Tensor`, having shape `[B1, ..., Bb, n, p]`.
      scale_row: Instance of `LinearOperator` with the same `dtype` as `loc`
        and shape `[B1, ..., Bb, n, n]`.
      scale_column: Instance of `LinearOperator` with the same `dtype` as `loc`
        and shape `[B1, ..., Bb, p, p]`.
      validate_args: Python `bool`, default `False`. Whether to validate input
        with asserts. If `validate_args` is `False`, and the inputs are
        invalid, correct behavior is not guaranteed.
      allow_nan_stats: Python `bool`, default `True`. If `False`, raise an
        exception if a statistic (e.g. mean/mode/etc...) is undefined for any
        batch member If `True`, batch members with valid parameters leading to
        undefined statistics will return NaN for this statistic.
      name: The name to give Ops created by the initializer.
    """
    ...
  
  @property
  def df(self):
    """Distribution parameter for degrees of freedom."""
    ...
  
  @property
  def loc(self):
    """Distribution parameter for the mean."""
    ...
  
  @property
  def scale_row(self): # -> Any:
    """Distribution parameter for row scale."""
    ...
  
  @property
  def scale_column(self): # -> Any:
    """Distribution parameter for column scale."""
    ...
  


